---
# Network Config
network_interfaces:
  - ifname: eth0
    zone: internal
    ip4: "{{ lab_resolver_ip }}/24"
    gw4: "{{ lab_router_internal_ip }}"
    dns4:
      - "{{ lab_bootstrap_dns_ip }}"
    conn_name: internal-static
    default_conn_name: "cloud-init eth0"

# Hosts File Config
hosts_file_entries:
  - address: "{{ lab_resolver_ip }}"
    canonical: "dns.{{ lab_domain }}"
    aliases:
      - dns
      - dns-01

# Firewall Config
firewall_zone_ports:
  - zone: internal
    port: 53
    proto: udp

  - zone: internal
    port: 53
    proto: tcp

# BIND9 Config
bind9_enabled: true
bind9_mode: resolver

bind9_listen_ipv4:
  - 127.0.0.1
  - "{{ bind9_dns_resolver_ip }}"

bind9_forwarders:
  - "{{ lab_bootstrap_dns_ip }}"

bind9_zones:
  - name: "{{ bind9_nasa_root_forward_zone }}"
    type: static-stub
    forwarders: []
    server_addresses:
      - "{{ bind9_nasa_root_ip }}"

  - name: "{{ bind9_nasa_root_reverse_zone }}"
    type: static-stub
    forwarders: []
    server_addresses:
      - "{{ bind9_nasa_root_ip }}"

  - name: "{{ bind9_vpn_child_reverse_zone_name }}"
    type: forward
    forward: only
    forwarders:
      - "{{ bind9_primary_ns_ip }}"

  - name: "{{ bind9_lab_forward_zone }}"
    type: forward
    forward: only
    forwarders:
      - "{{ bind9_primary_ns_ip }}"

  - name: "{{ bind9_lab_reverse_superzone }}"
    type: forward
    forward: only
    forwarders:
      - "{{ bind9_primary_ns_ip }}"
