---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of docker role"

- name: Validate Docker Role Variables
  ansible.builtin.import_tasks: assert.yml

- name: Setup Docker
  ansible.builtin.import_tasks: setup.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of docker role"
