---
# Network Config
network_interfaces:
  - ifname: eth0
    zone: dmz
    ip4: 172.16.0.53/24
    gw4: 172.16.0.254
    dns4:
      - 8.8.8.8
      - 1.1.1.1
    conn_name: dmz-static
    default_conn_name: "cloud-init eth0"

# WireGuard Config
wireguard_enabled: true

# Firewall Config
firewall_custom_zones:
  - vpn

firewall_bindings:
  - ifname: wg0
    zone: vpn

firewall_zone_ports:
  - zone: dmz
    port: 53
    proto: udp

  - zone: dmz
    port: 53
    proto: tcp

  - zone: vpn
    port: 53
    proto: udp

  - zone: vpn
    port: 53
    proto: tcp

firewall_rich_rules:
  - zone: vpn
    rule: 'rule service name="ssh" reject'

# BIND9 Config
bind9_enabled: true
bind9_mode: authoritative_secondary
bind9_listen_ipv4:
  - 127.0.0.1
  - 172.16.0.53
