---
# Network Config
network_interfaces:
  - ifname: eth0
    zone: internal
    ip4: 172.16.1.10/24
    gw4: 172.16.1.254
    dns4:
      - 172.16.1.153
      - 1.1.1.1
    conn_name: internal-static
    default_conn_name: "cloud-init eth0"

network_bootstrap_dns4:
  - 1.1.1.1

# Firewall Config
firewall_zone_ports:
  - zone: internal
    port: 636
    proto: tcp

firewall_rich_rules:
  - zone: internal
    rule: 'rule family="ipv4" source address="172.16.0.1/32" port port="2049" protocol="tcp" accept'
  - zone: internal
    rule: 'rule family="ipv4" source address="172.16.0.2/32" port port="2049" protocol="tcp" accept'

# Service enablement
openldap_enabled: true
nfs_server_enabled: true
nfs_enabled: true
