---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of openldap role"

- name: "PHASE [main : Validate Variables]"
  ansible.builtin.import_tasks: assert.yml

- name: "PHASE [main : Configure OpenLDAP]"
  ansible.builtin.import_tasks: setup.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of openldap role"
