---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of network role"

- name: "PHASE [main : Validate Network Role Variables]"
  ansible.builtin.import_tasks: assert.yml

- name: "PHASE [main : Configure Network Interfaces]"
  ansible.builtin.import_tasks: setup.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of network role"
