---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of network role"

- name: Validate Network Role Variables
  ansible.builtin.import_tasks: assert.yml

- name: Configure Network Interfaces
  ansible.builtin.import_tasks: setup.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of network role"
