# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/inventory.json
---
all:
  vars:
    ansible_user: student

  children:
    router:
      hosts:
        router-01:
          ansible_host: 127.0.0.1
          ansible_port: 2787

    dmz:
      hosts:
        dmz-agent-01:
          ansible_host: 172.16.0.123
          ansible_port: 22
          ansible_ssh_common_args: >-
            -o ProxyJump=student@127.0.0.1:2787

    internal:
      hosts:
        internal-agent-01:
          ansible_host: 172.16.1.123
          ansible_port: 22
          ansible_ssh_common_args: >-
            -o ProxyJump=student@127.0.0.1:2787
