---
# Network Config
network_interfaces:
  - ifname: eth0
    zone: dmz
    ip4: "{{ lab_dmz_client_ip }}/24"
    gw4: "{{ lab_router_dmz_ip }}"
    dns4:
      - "{{ lab_resolver_ip }}"
      - "{{ lab_bootstrap_dns_ip }}"
    conn_name: dmz-static
    default_conn_name: "cloud-init eth0"

network_bootstrap_dns4:
  - "{{ lab_bootstrap_dns_ip }}"

# Hosts File Config
hosts_file_entries:
  - address: "{{ lab_dmz_client_ip }}"
    canonical: "client.{{ lab_domain }}"
    aliases:
      - client
      - dmz-client-01

# WireGuard Config
wireguard_enabled: true

# Firewall Config
firewall_custom_zones:
  - vpn

firewall_bindings:
  - ifname: wg0
    zone: vpn
