---
- name: "PHASE [install : START]"
  become: false
  ansible.builtin.debug:
    msg: "Install mail packages"

- name: "PHASE [install : Enable EPEL Repository For OpenDKIM]"
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: "PHASE [install : Install Mail Packages]"
  ansible.builtin.dnf:
    name: "{{ mail_postfix_packages + mail_dovecot_packages + mail_opendkim_packages }}"
    state: present

- name: "PHASE [install : END]"
  become: false
  ansible.builtin.debug:
    msg: "Completed install phase"
