---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of mail role"

- name: "PHASE [main : Validate Variables]"
  ansible.builtin.import_tasks: assert.yml

- name: "PHASE [main : Install Packages]"
  ansible.builtin.import_tasks: install.yml

- name: "PHASE [main : Create vmail Identity And Passwd-File]"
  ansible.builtin.import_tasks: users.yml

- name: "PHASE [main : Deploy TLS Certificates]"
  ansible.builtin.import_tasks: tls.yml

- name: "PHASE [main : Configure Dovecot]"
  ansible.builtin.import_tasks: dovecot.yml

- name: "PHASE [main : Configure OpenDKIM Signing]"
  ansible.builtin.import_tasks: opendkim.yml

- name: "PHASE [main : Configure Postfix]"
  ansible.builtin.import_tasks: postfix.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of mail role"
