---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of mail role"

- name: "PHASE [main : Validate Variables]"
  ansible.builtin.import_tasks: assert.yml

- name: "PHASE [main : Install Packages]"
  ansible.builtin.import_tasks: install.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of mail role"
