# yaml-language-server: $schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/schema-network-config-v2.json
---
version: 2
renderer: NetworkManager
ethernets:
  eth0:
    dhcp4: false
    dhcp6: false
    addresses:
      - 172.16.1.53/24
    routes:
      - to: 0.0.0.0/0
        via: 172.16.1.254
    nameservers:
      addresses: [8.8.8.8, 1.1.1.1]
