---
# Prerequisites:
#   - bootstrap.yml
#   - dns_configure.yml
#   - ldap_configure.yml

- name: Mail Service Configuration
  hosts: mail
  gather_facts: true
  become: true
  roles:
    - role: mail
      when: mail_enabled | default(false) | bool
