---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of ldap-client role"

- name: "PHASE [main : Validate Variables]"
  ansible.builtin.import_tasks: assert.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of ldap-client role"
