---
- name: "PHASE [handler : Reactivate Changed NetworkManager Connections]"
  ansible.builtin.command:
    argv:
      - nmcli
      - connection
      - up
      - "{{ item.item.conn_name }}"
  loop: "{{ network_configure_interfaces.results | default([]) }}"
  loop_control:
    label: "{{ item.item.conn_name }}"
  when: item.changed
  changed_when: true
