---
# Shared LDAP identity
ldap_server_host: ldap-01
ldap_server_ip: "{{ hostvars[ldap_server_host].ansible_host }}"
ldap_domain: "{{ bind9_forward_zone_name }}"

ldap_base_dn: "dc={{ ldap_domain | regex_replace('\\.', ',dc=') }}"
ldap_server_fqdn: "ldap.{{ ldap_domain }}"
ldap_server_uri: "ldaps://{{ ldap_server_fqdn }}:636"

# SSH public key shared by all LDAP users
ldap_default_user_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMUa1AsYerXm5/QVrTZ7QxtkcCUfuXop004xu2hOBxNY 2026 NAP"

# Directory Information Tree containers
ldap_ous:
  - People
  - Group
  - Ppolicy
  - SUDOers
  - Fortune

# LDAP groups (posixGroup)
ldap_groups:
  ta:
    gid: 10000
    member_uids: [generalta, mailta]

  stu:
    gid: 20000
    member_uids: [stu]

# LDAP users
ldap_users:
  generalta:
    uid_number: 10000
    gid_number: 10000
    home: /u/ta/generalta
    mail: "generalta@{{ ldap_domain }}"
    groups: [ta]
    totp_required: true
    ssh_public_key: "{{ ldap_default_user_ssh_public_key }}"
    password_hash_key: generalta

  mailta:
    uid_number: 10001
    gid_number: 10000
    home: /u/ta/mailta
    mail: "mailta@{{ ldap_domain }}"
    groups: [ta]
    totp_required: false
    ssh_public_key: "{{ ldap_default_user_ssh_public_key }}"
    password_hash_key: mailta

  stu:
    uid_number: 20000
    gid_number: 20000
    home: /u/stu/stu
    mail: "stu@{{ ldap_domain }}"
    groups: [stu]
    totp_required: true
    ssh_public_key: "{{ ldap_default_user_ssh_public_key }}"
    password_hash_key: stu
