---
- name: "PHASE [handler : Restart Postfix]"
  ansible.builtin.systemd_service:
    name: "{{ mail_postfix_service_name }}"
    state: restarted

- name: "PHASE [handler : Restart Dovecot]"
  ansible.builtin.systemd_service:
    name: "{{ mail_dovecot_service_name }}"
    state: restarted

- name: "PHASE [handler : Restart OpenDKIM]"
  ansible.builtin.systemd_service:
    name: "{{ mail_opendkim_service_name }}"
    state: restarted

- name: "PHASE [handler : Restart List API]"
  ansible.builtin.systemd_service:
    name: "{{ mail_list_api_service_name }}"
    state: restarted

- name: "PHASE [handler : Restart Filter Milter]"
  ansible.builtin.systemd_service:
    name: "{{ mail_filter_milter_service_name }}"
    state: restarted
