---
- name: "PHASE [setup : START]"
  become: false
  ansible.builtin.debug:
    msg: "Set up bind9 configuration workflow"

- name: "PHASE [setup : END]"
  become: false
  ansible.builtin.debug:
    msg: "Completed setup phase"