---
- name: "PHASE [setup : START]"
  become: false
  ansible.builtin.debug:
    msg: "Set up bind9 configuration workflow"

- name: "PHASE [setup : Install bind9 Packages]"
  ansible.builtin.import_tasks: install.yml

- name: "PHASE [setup : Generate bind9 Configuration]"
  ansible.builtin.import_tasks: config.yml

- name: "PHASE [setup : Start And Enable bind9 Service]"
  ansible.builtin.import_tasks: service.yml

- name: "PHASE [setup : Verify bind9 Configuration And Service]"
  ansible.builtin.import_tasks: verify.yml

- name: "PHASE [setup : END]"
  become: false
  ansible.builtin.debug:
    msg: "Completed setup phase"
