---
- name: "START"
  become: false
  ansible.builtin.debug:
    msg: "Starting execution of wireguard role"

- name: "PHASE [main : Validate WireGuard Role Variables]"
  ansible.builtin.import_tasks: assert.yml

- name: "PHASE [main : Configure WireGuard]"
  ansible.builtin.import_tasks: setup.yml

- name: "END"
  become: false
  ansible.builtin.debug:
    msg: "Completed execution of wireguard role"
